Updated dockerfile to reflect changes to the function
Dockerfile:10
--------------------
   8 |
   9 |     # Copy function code
  10 | >>> COPY main.py "sfc_lambda"
  11 |
  12 |     # Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref h6giyvek9vdrghqvottimsw7l::til39d5rxb4fl8guqz2s2v0ka: "/main.py": not found

Exited with code exit status 1