Path needs to be on the copy not the install
Dockerfile:8
--------------------
   6 |     WORKDIR /sfc_lambda
   7 |
   8 | >>> COPY requirements.txt  .
   9 |     RUN  pip3 install -r /lambdas/create_dataset_snapshot/requirements.txt --target .
  10 |
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref lkutiefou5o2i0z12wztvglkl::h9rafdnqbtr812pv7ai4ev6gz: "/requirements.txt": not found